version: '3.8'

services:
  # PostgreSQL 17.5 Database
  postgres:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_DB: powerorchestrator_dev
      POSTGRES_USER: powerorch
      POSTGRES_PASSWORD: PowerOrch2025!
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U powerorch -d powerorchestrator_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
        -c shared_buffers=256MB
        -c max_connections=200
        -c effective_cache_size=1GB
        -c maintenance_work_mem=64MB
        -c checkpoint_completion_target=0.9
        -c wal_buffers=16MB
        -c default_statistics_target=100
        -c random_page_cost=1.1
        -c effective_io_concurrency=200
        -c work_mem=4MB
        -c min_wal_size=1GB
        -c max_wal_size=4GB

  # Redis 8.0.3 Cache
  redis:
    image: redis:8.0.3-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
        --appendonly yes
        --requirepass PowerOrchRedis2025!
        --maxmemory 512mb
        --maxmemory-policy allkeys-lru
        --tcp-keepalive 300
        --timeout 0
        --save 900 1
        --save 300 10
        --save 60 10000
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Seq Structured Logging
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: $2a$10$Ks6Ks6Ks6Ks6Ks6Ks6Ks6Ks6Ks6Ks6Ks6Ks6Ks6Ks6Ks6Ks6K  # "admin"
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  seq_data:
    driver: local

networks:
  default:
    name: powerorchestrator_dev
    driver: bridge