name: ✨ Feature Request
description: Suggest a new feature or enhancement for PowerOrchestrator
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # ✨ Feature Request
        
        Thank you for suggesting a new feature for PowerOrchestrator! Your ideas help us build a better PowerShell orchestration platform.
        
        **Before submitting:**
        - Search existing issues and discussions for similar requests
        - Consider how this feature aligns with PowerOrchestrator's enterprise focus
        - Think about the impact on existing users and workflows

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A brief summary of the requested feature
      placeholder: Provide a concise summary of the feature you'd like to see...
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which area of PowerOrchestrator does this feature relate to?
      options:
        - PowerShell Script Orchestration
        - GitHub Integration & Repository Management
        - Security & Authentication
        - Performance & Optimization
        - Material Design UI/UX
        - Database & Data Management
        - Caching & Redis Operations
        - API & Integration
        - Monitoring & Logging
        - Documentation & Help
        - DevOps & Deployment
        - Enterprise Features
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the current limitation or challenge that this feature would address.
        
        Examples:
        - Current workflow is inefficient because...
        - Users struggle with...
        - Enterprise environments need...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        Provide a detailed description of how you envision this feature working.
        
        Consider:
        - User interface changes
        - API modifications
        - PowerShell integration points
        - GitHub workflow impacts
        - Security implications
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Specific scenarios where this feature would be valuable
      placeholder: |
        Provide specific examples of how this feature would be used:
        
        **Use Case 1:**
        - User: [type of user]
        - Scenario: [what they're trying to do]
        - Benefit: [how this feature helps]
        
        **Use Case 2:**
        - User: [type of user]
        - Scenario: [what they're trying to do]
        - Benefit: [how this feature helps]
    validations:
      required: true

  - type: checkboxes
    id: powershell-features
    attributes:
      label: PowerShell Orchestration Features
      description: Which PowerShell capabilities would this feature involve?
      options:
        - label: Script Execution & Management
        - label: Module & Dependency Handling
        - label: Remote Execution & PSRemoting
        - label: Workflow & Pipeline Management
        - label: Error Handling & Retry Logic
        - label: PowerShell Core & Windows PowerShell Compatibility
        - label: Script Validation & Security Scanning
        - label: Performance Monitoring & Profiling

  - type: checkboxes
    id: github-features
    attributes:
      label: GitHub Integration Features
      description: Which GitHub integration aspects would this feature affect?
      options:
        - label: Repository Discovery & Management
        - label: Branch & Tag Operations
        - label: File & Content Operations
        - label: Authentication & Permissions
        - label: Webhooks & Event Handling
        - label: Actions & Workflows Integration
        - label: Enterprise GitHub Support
        - label: Rate Limiting & API Management

  - type: checkboxes
    id: ui-features
    attributes:
      label: Material Design UI Features
      description: Which UI components or patterns would this feature involve?
      options:
        - label: Navigation & Menu Systems
        - label: Data Display & Tables
        - label: Forms & Input Controls
        - label: Charts & Visualizations
        - label: Real-time Updates & Notifications
        - label: Theme & Customization
        - label: Mobile & Responsive Design
        - label: Accessibility Features

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Critical - Blocking key workflows
        - High - Significant improvement needed
        - Medium - Nice to have enhancement
        - Low - Minor convenience feature
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature might be to implement?
      options:
        - Simple - Minor UI change or configuration option
        - Moderate - New component or API endpoint
        - Complex - Major architectural change
        - Very Complex - Fundamental system redesign
        - Unknown - Unsure of implementation complexity
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered complete?
      placeholder: |
        Define clear, testable criteria that indicate when this feature is done:
        
        - [ ] Feature requirement 1
        - [ ] Feature requirement 2
        - [ ] Performance requirement (if applicable)
        - [ ] Security requirement (if applicable)
        - [ ] Documentation requirement
        - [ ] Testing requirement
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered alternative approaches?
      placeholder: |
        Describe any alternative solutions or workarounds you've considered.
        
        Why do you prefer your proposed solution over these alternatives?
    validations:
      required: false

  - type: textarea
    id: enterprise-considerations
    attributes:
      label: Enterprise Environment Considerations
      description: How would this feature work in enterprise environments?
      placeholder: |
        Consider enterprise-specific requirements:
        
        **Security:** How does this feature handle sensitive data?
        **Scalability:** How does this work with large numbers of users/scripts?
        **Compliance:** Any regulatory or audit requirements?
        **Integration:** How does this work with enterprise systems?
        **Governance:** How do administrators control this feature?
    validations:
      required: false

  - type: textarea
    id: migration-impact
    attributes:
      label: Migration & Backward Compatibility
      description: How would this feature affect existing users?
      placeholder: |
        Consider the impact on existing users:
        
        **Breaking Changes:** Would this break existing functionality?
        **Migration Path:** How would users upgrade to use this feature?
        **Configuration:** Any new configuration requirements?
        **Training:** Would users need training on this feature?
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would be helpful
      placeholder: |
        Add any other context, screenshots, mockups, or references that would help understand this feature request.
        
        You can paste images directly into this text area.
        
        Include links to similar features in other tools if relevant.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would like to help implement this feature
        - label: I can provide testing and feedback
        - label: I can help with documentation
        - label: I can provide enterprise testing scenarios

  - type: checkboxes
    id: terms
    attributes:
      label: Submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions for similar requests
          required: true
        - label: I have provided a clear problem statement and proposed solution
          required: true
        - label: I have considered the enterprise and security implications
          required: true
        - label: This feature aligns with PowerOrchestrator's goals as a PowerShell orchestration platform
          required: true