name: 🔒 Security Concern
description: Report security vulnerabilities or concerns in PowerOrchestrator
title: "[SECURITY] "
labels: ["security", "needs-triage", "priority-high"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # 🔒 Security Concern
        
        **IMPORTANT:** If you believe you have discovered a critical security vulnerability, please follow our responsible disclosure process:
        
        📧 **Email:** [security@valhallatech.com](mailto:security@valhallatech.com)  
        🔐 **Encrypt:** Use our PGP key for sensitive reports  
        ⏰ **Response:** We respond to security reports within 24 hours  
        
        For non-critical security concerns, general security questions, or security feature requests, please use this template.
        
        **Security is paramount for enterprise PowerShell orchestration. All security reports are treated with the highest priority.**

  - type: dropdown
    id: security-type
    attributes:
      label: Security Issue Type
      description: What type of security concern is this?
      options:
        - Vulnerability Report (Non-Critical)
        - Security Feature Request
        - Authentication/Authorization Issue
        - Data Privacy Concern
        - Security Configuration Question
        - Audit/Compliance Question
        - Security Best Practices
        - Third-Party Security Integration
    validations:
      required: true

  - type: dropdown
    id: severity-level
    attributes:
      label: Security Severity Level
      description: How would you classify the severity of this security concern?
      options:
        - Critical - Immediate system compromise possible
        - High - Significant security risk
        - Medium - Moderate security concern
        - Low - Minor security improvement
        - Informational - Security question or guidance needed
    validations:
      required: true

  - type: textarea
    id: security-summary
    attributes:
      label: Security Issue Summary
      description: Brief description of the security concern
      placeholder: |
        Provide a clear, concise summary of the security issue or concern.
        
        **Note:** Avoid including specific exploit details in public issues. Use general terms and contact security@valhallatech.com for sensitive details.
    validations:
      required: true

  - type: dropdown
    id: affected-component
    attributes:
      label: Affected Component
      description: Which PowerOrchestrator component is involved?
      options:
        - PowerShell Script Execution Engine
        - Authentication System
        - Authorization & Access Control
        - GitHub Integration & API
        - Database Layer (PostgreSQL)
        - Caching Layer (Redis)
        - MAUI User Interface
        - REST API Layer
        - Configuration Management
        - Logging & Audit System
        - Identity Management
        - Session Management
        - File System Access
        - Network Communications
    validations:
      required: true

  - type: checkboxes
    id: security-categories
    attributes:
      label: Security Categories
      description: Which security aspects does this concern relate to? (Select all applicable)
      options:
        - label: Code Injection (PowerShell, SQL, etc.)
        - label: Authentication Bypass
        - label: Authorization Escalation
        - label: Data Exposure/Leakage
        - label: Cross-Site Scripting (XSS)
        - label: Cross-Site Request Forgery (CSRF)
        - label: Insecure Direct Object References
        - label: Security Misconfiguration
        - label: Cryptographic Issues
        - label: Session Management
        - label: Input Validation
        - label: Output Encoding
        - label: File Upload Security
        - label: API Security
        - label: Container/Docker Security

  - type: textarea
    id: powershell-security
    attributes:
      label: PowerShell Security Context
      description: Security details specific to PowerShell script execution
      placeholder: |
        **Script Execution Security:**
        - Execution Policy: (Current setting, bypass attempts)
        - Script Signing: (Required, bypassed, certificate issues)
        - Constrained Language Mode: (Enabled, bypassed)
        - Remote Execution: (PSRemoting, authentication, authorization)
        - Module Loading: (Untrusted modules, path manipulation)
        
        **Script Content Security:**
        - Input Validation: (User input handling, injection points)
        - Output Sanitization: (Sensitive data exposure)
        - Credential Handling: (Storage, transmission, access)
        - External Commands: (System calls, executable invocation)
        - File System Access: (Path traversal, permission issues)
        
        **Execution Environment:**
        - User Context: (Privileges, service accounts)
        - Network Access: (Outbound connections, proxy bypass)
        - Registry Access: (Sensitive keys, modification rights)
        - Environment Variables: (Sensitive data, injection)
    validations:
      required: false

  - type: textarea
    id: authentication-security
    attributes:
      label: Authentication & Authorization Details
      description: Security details for identity and access management
      placeholder: |
        **Authentication Mechanisms:**
        - Method Used: (JWT, OAuth, SAML, Certificate)
        - Token Security: (Storage, transmission, expiration)
        - Password Policies: (Strength, rotation, hashing)
        - Multi-Factor Auth: (Implementation, bypass potential)
        - Session Management: (Creation, validation, termination)
        
        **Authorization Controls:**
        - Role-Based Access: (RBAC implementation, escalation)
        - Permission Model: (Granularity, inheritance, conflicts)
        - Resource Protection: (Access controls, validation)
        - API Authorization: (Endpoint security, token validation)
        - Administrative Access: (Super-user controls, separation)
        
        **Identity Integration:**
        - Active Directory: (Integration security, LDAP injection)
        - External IdP: (SAML security, token validation)
        - Service Accounts: (Privilege levels, rotation)
        - GitHub Authentication: (OAuth scope, token security)
    validations:
      required: false

  - type: textarea
    id: data-security
    attributes:
      label: Data Security & Privacy Details
      description: Information about data protection and privacy concerns
      placeholder: |
        **Data Classification:**
        - Data Types: (Personal, financial, health, intellectual property)
        - Sensitivity Level: (Public, internal, confidential, restricted)
        - Regulatory Requirements: (GDPR, HIPAA, SOX, PCI-DSS)
        - Retention Policies: (Storage duration, deletion requirements)
        
        **Data Protection:**
        - Encryption at Rest: (Database, file system, cache)
        - Encryption in Transit: (TLS versions, certificate management)
        - Key Management: (Storage, rotation, access control)
        - Data Masking: (Logging, UI display, export)
        - Backup Security: (Encryption, access control, retention)
        
        **Data Flow Security:**
        - Input Sanitization: (Validation, encoding, filtering)
        - Output Encoding: (Context-aware, character sets)
        - Data Transmission: (Protocols, encryption, integrity)
        - Third-Party Sharing: (APIs, integrations, consent)
        - Audit Logging: (Data access, modifications, exports)
    validations:
      required: false

  - type: textarea
    id: github-integration-security
    attributes:
      label: GitHub Integration Security
      description: Security aspects of GitHub integration and repository management
      placeholder: |
        **GitHub Authentication:**
        - Token Types: (Personal, OAuth App, GitHub App)
        - Scope Management: (Minimal permissions, scope creep)
        - Token Storage: (Encryption, rotation, revocation)
        - Organization Access: (Permission levels, enterprise controls)
        
        **Repository Security:**
        - Access Controls: (Public/private repo handling)
        - Branch Protection: (Rules, bypass attempts)
        - Webhook Security: (Signature validation, replay protection)
        - Content Validation: (Malicious code detection, scanning)
        - Rate Limiting: (API quotas, abuse prevention)
        
        **Enterprise Features:**
        - SAML SSO: (Implementation, bypass potential)
        - IP Allowlisting: (Bypass attempts, validation)
        - Audit Logging: (API access, repository operations)
        - Advanced Security: (Secret scanning, dependency alerts)
    validations:
      required: false

  - type: textarea
    id: infrastructure-security
    attributes:
      label: Infrastructure Security Details
      description: Security concerns related to databases, caching, and infrastructure
      placeholder: |
        **Database Security (PostgreSQL):**
        - Connection Security: (SSL/TLS, certificate validation)
        - Authentication: (Password policies, certificate auth)
        - Authorization: (Role-based access, row-level security)
        - SQL Injection: (Parameter binding, input validation)
        - Audit Logging: (Access logs, query logs, data changes)
        
        **Cache Security (Redis):**
        - Authentication: (Password policies, ACL configuration)
        - Network Security: (TLS encryption, network isolation)
        - Data Encryption: (At-rest encryption, key management)
        - Access Control: (Command restrictions, user isolation)
        - Persistence Security: (RDB/AOF file protection)
        
        **Container Security:**
        - Image Security: (Base image vulnerabilities, scanning)
        - Runtime Security: (User privileges, resource limits)
        - Network Security: (Service isolation, firewall rules)
        - Secrets Management: (Environment variables, mounted secrets)
        - Registry Security: (Image signing, private registries)
    validations:
      required: false

  - type: textarea
    id: impact-assessment
    attributes:
      label: Security Impact Assessment
      description: Potential impact and exploitation scenarios
      placeholder: |
        **Potential Impact:**
        - Confidentiality: (Data exposure, unauthorized access)
        - Integrity: (Data modification, system tampering)
        - Availability: (Service disruption, DoS potential)
        - Authentication: (Bypass, impersonation)
        - Authorization: (Privilege escalation, unauthorized actions)
        
        **Exploitation Scenarios:**
        - Attack Vector: (Local, network, web-based)
        - Prerequisites: (Authentication required, specific conditions)
        - Complexity: (Simple, moderate, complex exploitation)
        - User Interaction: (Required, social engineering aspects)
        - Persistence: (Temporary, permanent system changes)
        
        **Business Impact:**
        - Regulatory Compliance: (Violation potential, penalties)
        - Reputation Risk: (Public disclosure, customer trust)
        - Financial Impact: (Direct costs, liability, lost revenue)
        - Operational Impact: (Service disruption, recovery time)
    validations:
      required: false

  - type: textarea
    id: reproduction-info
    attributes:
      label: Reproduction Information
      description: How to reproduce this security issue (use general terms for public issues)
      placeholder: |
        **General Reproduction Steps:**
        1. Configure environment with...
        2. Authenticate as user with role...
        3. Access component/feature...
        4. Perform action that demonstrates the security concern...
        
        **Environment Requirements:**
        - Specific configuration settings
        - User role/permission requirements
        - Network access requirements
        - Software version dependencies
        
        **Note:** For sensitive vulnerabilities, provide only general steps here and email detailed reproduction steps to security@valhallatech.com
    validations:
      required: false

  - type: textarea
    id: mitigation-recommendations
    attributes:
      label: Suggested Mitigations
      description: Your recommendations for addressing this security concern
      placeholder: |
        **Immediate Mitigations:**
        - Configuration changes to reduce risk
        - Access control modifications
        - Monitoring enhancements
        - User behavior recommendations
        
        **Long-term Solutions:**
        - Code changes required
        - Architecture improvements
        - Process enhancements
        - Security control additions
        
        **Industry Best Practices:**
        - Reference standards (OWASP, NIST, ISO 27001)
        - Similar implementations in other tools
        - Security frameworks applicable
    validations:
      required: false

  - type: textarea
    id: compliance-considerations
    attributes:
      label: Compliance & Regulatory Considerations
      description: Regulatory or compliance aspects of this security concern
      placeholder: |
        **Applicable Regulations:**
        - GDPR (General Data Protection Regulation)
        - HIPAA (Health Insurance Portability and Accountability Act)
        - SOX (Sarbanes-Oxley Act)
        - PCI-DSS (Payment Card Industry Data Security Standard)
        - FISMA (Federal Information Security Management Act)
        - Industry-specific regulations
        
        **Compliance Requirements:**
        - Audit trail requirements
        - Data protection mandates
        - Access control standards
        - Incident reporting obligations
        - Risk assessment needs
        
        **Enterprise Security Frameworks:**
        - NIST Cybersecurity Framework
        - ISO 27001/27002
        - CIS Controls
        - OWASP Application Security
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information about this security concern
      placeholder: |
        **Related Security Issues:**
        - Similar vulnerabilities in other components
        - Chain of vulnerabilities that could be combined
        - Dependencies with known security issues
        
        **Security Testing:**
        - Penetration testing findings
        - Security scanning results
        - Code analysis results
        - Vulnerability assessments
        
        **Enterprise Environment:**
        - Specific enterprise security requirements
        - Integration with security tools (SIEM, DLP, etc.)
        - Corporate security policies applicable
        - Third-party security assessments
        
        **Note:** Attach files or screenshots that don't contain sensitive information. For sensitive materials, use secure email communication.
    validations:
      required: false

  - type: checkboxes
    id: responsible-disclosure
    attributes:
      label: Responsible Disclosure Acknowledgment
      description: Please confirm your understanding of our security practices
      options:
        - label: I understand that critical vulnerabilities should be reported privately to security@valhallatech.com
          required: true
        - label: I have not included sensitive exploit details or proof-of-concept code in this public issue
          required: true
        - label: I will follow responsible disclosure practices and allow time for fixes before public disclosure
          required: true
        - label: I understand that security issues receive high priority and will be addressed promptly
          required: true

  - type: checkboxes
    id: submission-terms
    attributes:
      label: Submission Checklist
      description: Please confirm the following
      options:
        - label: I have assessed the security impact and classified the severity appropriately
          required: true
        - label: I have searched for existing security issues to avoid duplicates
          required: true
        - label: I have provided sufficient detail for security assessment and remediation
          required: true
        - label: I understand this issue will be handled according to our security response process
          required: true